# Generated by Django 2.1.2 on 2018-11-07 20:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articleupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('postdate', models.DateField(default=django.utils.timezone.now)),
                ('imageurl', models.TextField()),
            ],
        ),
    ]
