# Generated by Django 2.1.2 on 2018-11-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_articleupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleupload',
            name='articleurl',
            field=models.TextField(default='www.google.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articleupload',
            name='subreddit',
            field=models.CharField(default='www.google.com', max_length=50),
            preserve_default=False,
        ),
    ]
