# Generated by Django 2.1.2 on 2018-11-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_articlereview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlereview',
            name='author',
        ),
        migrations.RemoveField(
            model_name='articlereview',
            name='post',
        ),
        migrations.AddField(
            model_name='articleupload',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='articleupload',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='articleupload',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='articleupload',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ArticleReview',
        ),
    ]
