# Generated by Django 2.1.2 on 2019-02-24 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190223_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleupload',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='articleupload',
            name='bias',
        ),
        migrations.RemoveField(
            model_name='articleupload',
            name='conservative',
        ),
        migrations.RemoveField(
            model_name='articleupload',
            name='factual',
        ),
        migrations.RemoveField(
            model_name='articleupload',
            name='jscore',
        ),
        migrations.RemoveField(
            model_name='articleupload',
            name='liberal',
        ),
        migrations.RemoveField(
            model_name='articleupload',
            name='misleading',
        ),
        migrations.RemoveField(
            model_name='articleupload',
            name='notfactual',
        ),
    ]
